/**
 * Comment handler logic for Devvit Post Summarizer
 */

/**
 * Handle new comment submission
 */
export async function handleNewComment(
  event: any,
  { reddit, redis }: { reddit: any; redis: any }
): Promise<void> {
  const { postId } = event;
  const subreddit = event.subreddit?.name || (await reddit.getCurrentSubreddit());

  // Check if post has 75+ comments
  const comments = await reddit.getComments({
    postId: postId,
    limit: 100,
  });

  if (comments.length < 75) {
    console.log(`Post ${postId} has ${comments.length} comments, not enough for summary`);
    return;
  }

  // Check if already summarized
  const summaryKey = `summary:${postId}`;
  const existingSummary = await redis.get(summaryKey);
  if (existingSummary) {
    console.log(`Post ${postId} already summarized`);
    return;
  }

  // Trigger summarization
  await checkAndSummarize({ reddit, redis }, postId, subreddit);
}

/**
 * Check if post needs summarization and generate summary if so
 */
export async function checkAndSummarize(
  { reddit, redis }: { reddit: any; redis: any },
  postId: string,
  subreddit: string
): Promise<void> {
  try {
    console.log(`Starting summarization for post ${postId}`);

    // Get API key
    const apiKey = await getOpenRouterKey({ redis }, subreddit);
    if (!apiKey) {
      console.log(`No API key configured for r/${subreddit}`);
      return;
    }

    // Get post details
    const post = await reddit.getPostById(postId);
    const postTitle = post.title;
    const postBody = post.body || "";

    // Get comments
    const comments = await reddit.getComments({
      postId: postId,
      limit: 100,
    });

    // Prepare summary request
    const prompt = `Please summarize the following Reddit post and its top comments:

**Post Title:** ${postTitle}

**Post Body:**
${postBody}

**Top Comments:**
${comments.slice(0, 50).map((c: any) => `> ${c.author.name}: ${c.body}`).join('\n\n')}

Provide a concise summary of the main points and key discussions from the comments.`;

    // Call OpenRouter API
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'openai/gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are a helpful assistant that summarizes Reddit discussions concisely.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        max_tokens: 500,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`OpenRouter API error: ${response.status} ${errorText}`);
    }

    const data = await response.json();
    const summary = data.choices[0]?.message?.content || 'Failed to generate summary';

    // Post summary as a comment
    const summaryComment = await reddit.submitComment({
      postId: postId,
      text: `🤖 **AI Summary**

${summary}

---
*Summary generated by Devvit Post Summarizer*`
    });

    await reddit.distinguishComment({ id: summaryComment.id });

    // Mark as summarized
    const summaryKey = `summary:${postId}`;
    await redis.set(summaryKey, 'true');
    await redis.expire(summaryKey, 7 * 24 * 60 * 60); // 7 days

    console.log(`Successfully summarized post ${postId}`);

  } catch (error: any) {
    console.error(`Error summarizing post ${postId}:`, error);
  }
}

/**
 * Store OpenRouter API key for a subreddit
 */
export async function setOpenRouterKey(
  { redis }: { redis: any },
  subreddit: string,
  apiKey: string
): Promise<void> {
  const key = `apikey:${subreddit}`;
  await redis.set(key, apiKey);
}

/**
 * Get OpenRouter API key for a subreddit
 */
export async function getOpenRouterKey(
  { redis }: { redis: any },
  subreddit: string
): Promise<string | null> {
  const key = `apikey:${subreddit}`;
  return await redis.get(key);
}
