import { Devvit, TriggerContext } from '@devvit/public-api';

const COMMENT_THRESHOLD = 75;
const MAX_COMMENTS_FOR_SUMMARY = 50;
const OPENROUTER_MODEL = 'nvidia/nemotron-3-super-120b-a12b:free';
const OPENROUTER_URL = 'https://openrouter.ai/api/v1/chat/completions';

Devvit.configure({
  redditAPI: true,
  redis: true,
  http: {
    domains: ['openrouter.ai'],
  },
});

Devvit.addSettings([
  {
    name: 'openrouter-api-key',
    label: 'OpenRouter API Key',
    type: 'string',
    scope: 'installation',
    helpText: 'Your OpenRouter API key (from openrouter.ai/keys)',
  },
]);

// Shared summarization logic used by both the trigger and the menu item.
// `force` skips the Redis idempotency guard (used for manual mod triggers).
async function performSummary(
  postId: string,
  context: Pick<TriggerContext, 'reddit' | 'redis' | 'settings'>,
  force = false,
): Promise<'already_done' | 'no_api_key' | 'api_error' | 'success'> {
  const redisKey = `summarized:${postId}`;

  if (!force) {
    const alreadyDone = await context.redis.get(redisKey);
    if (alreadyDone) return 'already_done';
  }

  // Claim the job before any async work to prevent races
  await context.redis.set(redisKey, '1');

  // Fetch the full Post model for title
  const post = await context.reddit.getPostById(postId);

  // Fetch top comments
  const comments = await context.reddit.getComments({
    postId,
    sort: 'top',
    pageSize: MAX_COMMENTS_FOR_SUMMARY,
  }).all();

  const commentTexts = comments
    .slice(0, MAX_COMMENTS_FOR_SUMMARY)
    .filter((c) => c.body && c.body.trim().length > 0)
    .map((c, i) => `Comment ${i + 1} (${c.score} upvotes):\n${c.body.trim()}`)
    .join('\n\n---\n\n');

  const prompt = `You are a helpful Reddit moderator bot. A post titled "${post.title}" has reached many comments and you need to summarize the discussion.

Summarize the key themes, main opinions, interesting insights, and any notable points raised. Be neutral, concise, and helpful. Format the output with a short intro sentence, then bullet points for the main takeaways.

Post title: "${post.title}"

Top comments:
${commentTexts}`;

  const apiKey = await context.settings.get('openrouter-api-key');
  if (!apiKey) {
    console.error('No OpenRouter API key configured');
    return 'no_api_key';
  }

  let summary: string;
  try {
    const response = await fetch(OPENROUTER_URL, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://reddit.com',
        'X-Title': 'ICA Mod Bot',
      },
      body: JSON.stringify({
        model: OPENROUTER_MODEL,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!response.ok) {
      console.error(`OpenRouter API error: ${response.status} ${response.statusText}`);
      return 'api_error';
    }

    const data = await response.json();
    summary = data?.choices?.[0]?.message?.content;
    if (!summary) {
      console.error('No summary returned from OpenRouter');
      return 'api_error';
    }
  } catch (err) {
    console.error('Failed to call OpenRouter API:', err);
    return 'api_error';
  }

  const botComment = await context.reddit.submitComment({
    id: postId,
    text: `**[Bot Summary]** *This post has reached ${COMMENT_THRESHOLD}+ comments. Here's an AI-generated summary of the discussion:*\n\n${summary}\n\n---\n*^(This summary was automatically generated by a bot. It may not capture all nuances of the discussion.)*`,
  });

  await botComment.distinguish(true);

  return 'success';
}

// Automatic trigger: fires on every new comment
Devvit.addTrigger({
  event: 'CommentCreate',
  async onEvent(event, context) {
    const postId = event.comment?.postId;
    if (!postId) return;

    // Quick bail using event payload before making any API calls
    if ((event.post?.numComments ?? 0) < COMMENT_THRESHOLD) return;

    // Authoritative check with fresh data from the API
    const post = await context.reddit.getPostById(postId);
    if (post.numberOfComments < COMMENT_THRESHOLD) return;

    await performSummary(postId, context);
  },
});

// Manual trigger: mod-only post menu item for testing
Devvit.addMenuItem({
  label: 'Summarise this post',
  location: 'post',
  forUserType: 'moderator',
  async onPress(event, context) {
    const postId = event.targetId;

    context.ui.showToast('Generating summary, please wait...');

    // force=true bypasses the Redis guard so mods can re-trigger at any time
    const result = await performSummary(postId, context, true);

    if (result === 'already_done') {
      context.ui.showToast('Already summarized (this should not appear in forced mode).');
    } else if (result === 'no_api_key') {
      context.ui.showToast('Error: OpenRouter API key not configured.');
    } else if (result === 'api_error') {
      context.ui.showToast('Error calling the AI API. Check the logs.');
    } else {
      context.ui.showToast('Summary posted successfully!');
    }
  },
});

export default Devvit;
